version: '3.0'

volumes:
  vendor:

services:
  api:
    build:
      context: .
      dockerfile: golang/Dockerfile
    volumes:
      - ./go/src/api:/go/src/api
      - vendor:/go/src/api/vendor
    ports:
      - 5000:5000
    tty:
      true
