version: "3"

services:
  app:
    build: ./golang
    ports:
      - "5000:5000"
    volumes:
      - ./go:/go
    command: >
      bash -c "echo $PATH
      && cd /go/src/vocatuku_api && go build -o /go/src/vocatuku_api/target/exec 
      && /go/src/vocatuku_api/target/exec"
#    command: >
#      bash -c "echo $PATH
#      && go get -u github.com/goadesign/goa/...
#      && go get -u github.com/golang/dep/cmd/dep
#      && cd /go/src && goagen bootstrap -d api_design/voices -o /go/src/vocatuku_api 
#      && cd /go/src/vocatuku_api
#      && dep init
#      && dep ensure
#      && go build -o /go/src/vocatuku_api/target/exec 
#      && /go/src/vocatuku_api/target/exec"
