version: "3.3"

services:
  nginx:
    build: ./nginx
    volumes:
#      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
      - ./src:/usr/share/nginx/app
    ports:
      - 8080:80
    links:
      - fpm

  fpm:
    build: ./php-fpm
#    image: php:7-fpm-alpine
    volumes:
      - ./src:/usr/share/nginx/app
    command: >
      bash -c 'mkdir -p /usr/share/nginx/app &&
      cd /usr/share/nginx/app
      composer install'

#mkdir -p /usr/share/nginx/app \
#     && cd /usr/share/nginx/app \
#    && composer create-project laravel/laravel --prefer-dist sample 5.6

    expose:
      - 9000
