version: "3.3"

services:
  nginx_1:
    build: ./nginx_1
    volumes:
      - ./nginx_1/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx_1/log:/var/log/nginx
      - ./src_1:/usr/share/nginx/app
    ports:
      - 8081:80
    links:
      - fluentd_1
      - fpm

  fluentd_1:
    build: ./fluentd_1
    volumes:
      - ./fluentd_1/config:/fluentd/etc
      - ./fluentd_1/log:/var/log
      - ./nginx_1/log:/var/log/nginx
    ports:
      - 24225:24224
    links:
      - fluentd_aggregation

  nginx_2:
    build: ./nginx_2
    volumes:
      - ./nginx_2/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx_2/log:/var/log/nginx
      - ./src_2:/usr/share/nginx/app
    ports:
      - 8082:80
    links:
      - fluentd_2
      - fpm

  fluentd_2:
    build: ./fluentd_2
    volumes:
      - ./fluentd_2/config:/fluentd/etc
      - ./fluentd_2/log:/var/log
      - ./nginx_2/log:/var/log/nginx
    ports:
      - 24226:24224
    links:
      - fluentd_aggregation

  # fpm
  fpm:
    build: ./php-fpm
    volumes:
      - ./src_1:/usr/share/nginx/app
      - ./src_2:/usr/share/nginx/app
    expose:
      - 9000

  # fluentd aggregation
  fluentd_aggregation:
    build: ./fluentd_aggregation
    volumes:
      - ./fluentd_aggregation/config:/fluentd/etc
      - ./fluentd_aggregation/log:/var/log
    ports:
      - 24224:24224

  elasticsearch:
    build: ./elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
#    container_name: elasticsearch
    hostname: elasticsearch
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "xpack.security.enabled=false"
  kibana:
    build: ./kibana
    ports:
      - "5601:5601"
#    container_name: kibana
    links:
      - elasticsearch
