version: "3"

services:
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
      - ./nginx/html:/usr/share/nginx/html
    ports:
      - 8080:80
#    links:
#      - fluentd

#  fluentd:
#    build: ./fluentd
#    volumes:
#      - ./fluentd/config:/fluentd/etc
#      - ./fluentd/log:/var/log
#      - ./nginx/log:/var/log/nginx
#    extra_hosts:
#      - "local_dev:10.0.2.15"    
