version: "3.3"

services:
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
      - ./src:/usr/share/nginx/app
    ports:
      - 8080:80
    links:
      - fpm

  fpm:
    build: ./php-fpm
    volumes:
      - ./src:/usr/share/nginx/app
    expose:
      - 9000

  mysql:
    build: ./mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=passwd"
      - "MYSQL_DATABASE=mysqldb"
    hostname: dbserver
    restart: always

  redis:
    build: ./redis
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379
    restart: always
    command: redis-server --appendonly yes
